### ISSUE TITLE
Not working group

### ISSUE THREAD

**Issue by beoro** [razonyang/php-router#1]
`$router->handle('GET', '/', array('controller', 'home'));`

`$router->group('/admin', function(Router $group){
    $group->get('/dashboard', array('controller', 'admin'));
});`

**Comment by razonyang** [comment]
The request `path` and group's `prefix` should not begin with `/`.

```
$router->handle('GET', '', array('controller', 'home'));

$router->group('admin', function (Router $group) {
    $group->get('dashboard', array('controller', 'admin'));
});

var_dump($router->dispatch('GET', ''));
var_dump($router->dispatch('GET', 'admin/dashboard'));
```

Hope this helps :) @beoro
